=== doorhinges0/SmartServer/common/src/main/java/com/dtsjy/mdboss/common/export/config/entities.dtd
<!--
<!DOCTYPE entity-config SYSTEM "entities.dtd">
************************************************************
该dtd文件用于说明entities.xml文件的配置方式

entity-config为文档元素,含有最少一个entity子元素
************************************************************
-->
<!ELEMENT entity-config (entity+)>

<!--
***********************************************************
 entity元素指定一个要导出数据的VO(对于多表查询的时候,因为有多个VO,所以
 需要使用复杂查询的方式,建立一个虚拟VO).
 entity元素的name属性是必须的,name的值应为VO的全类名,以保持唯一;exceloutbean属性指定用于导出操作
 的bean类全名,该类继承com.sunrise.boss.ui.resmanage.common.excelout.ExceloutBean类,若没有
 设置该属性,则程序中默认使用com.sunrise.boss.ui.resmanage.common.excelout.ExceloutBean类.
 entiy元素含有delegate,formname,resbundle,outfilename,fields子元素,
 除了delegate元素外,其它的子元素必须要依声明的顺序存在.
***********************************************************
-->
<!ELEMENT entity (tableorview?,delegate,fields,headtitle?,endtitle?,beforewrite?,afterwrite?)>
<!ATTLIST entity 
			name ID #REQUIRED
			exceloutbean CDATA #IMPLIED
			showcount (yes|no) "no"
			sheetname CDATA #IMPLIED
>
<!--
***********************************************************
 delegate元素指定调用其方法获得查询数据及其记录数的代理类,该元素不是必需
 的,如果在excelout.xml文件没有指定,则程序中会使用
 "com.sunrise.boss.delegate.common.CommonDelegate"作为元素内容;
 
 delegate元素含有query,count两属性,query属性指定delegate类中用以获得
 查询数据的查询方法的名称,如果没有指定该属性的值程序中默认使用"doQuery"作为方法名;
 count属性指定delegate类中用以获得符合导出条件的 记录总数的方法名称,
 如果没有指定该属性的值,程序中默认使用"doCount"作为方法名.
***********************************************************
-->
<!ELEMENT tableorview (#PCDATA)>

<!ELEMENT delegate (query+)>
<!ATTLIST delegate 
	class CDATA #REQUIRED
>

<!ELEMENT query (query_sql*)>
<!ATTLIST query 
	methodtype (data_query|count_query) "data_query"
	methodname CDATA #REQUIRED
	querytype (normal|querybysql|querybynamesql) "normal"
	queryname CDATA #IMPLIED
	orderby CDATA #IMPLIED
>

<!ELEMENT query_sql (#PCDATA)>

<!ELEMENT formname (#PCDATA)>

<!--
***********************************************************
 指定VO的所有需要导出的字段,最少含有一个字段
***********************************************************
-->
<!ELEMENT fields (field+)>

<!--
***********************************************************
 指定需要导出的VO的单个字段,含有子元素definition,该子元素是可选的.
 
 name属性指定字段的名称(与VO里面定义一致).
 
 covertvalue属性指定该字段值在导出的时候是否需要进行转换,(譬如:套卡查询中,price字段导出
 的值为price/100),该属性的值只能是 字段名(+|-|*|/)数字的形式,若
 有特殊的实现,可以提供实现Excelout接口的实现类,实现接口的geValue
 方法.
 var属性指定值转换时需要赋值的变量(多个变量用逗号分隔),如若covertvalue的值为'price/100+addjust+receivable',
 则var的值应为'addjust,receivable',字段price的值默认添加.
 
 format与formattype属性用于定义导出数据的格式,如数字、日期的格式。
***********************************************************
-->
<!ELEMENT field (definition*)>
<!ATTLIST field 
	name CDATA #REQUIRED
	covertvalue CDATA #IMPLIED
	var CDATA #IMPLIED
	format (none|STRING|NUMBER|DATE|CODE2NAME) "none"
	formattype CDATA #IMPLIED
	style CDATA #IMPLIED
	titlename CDATA #IMPLIED
>

<!--
***********************************************************
 指定导出字段进行code2name翻译时用到的definition属性的值.
 该元素可包含字符数据或case子元素.
 
 若包含字符数据,则该字符数据为definition的值[该值有四种选择:
 系统参数($开头),配置方式(#开头),实现Code2name接口类的类short名,
 实现Excelout接口的类short名(以*开头)];
 
 若包含case子元素,则definition的值由case元素的内容决定,此时,
 definition元素应含有属性dependent,指定definition的值依赖于哪
 个字段(同一VO的字段)譬如:台帐查询中,typeid字段翻译所用到的definition的
 值依赖于sheetrestype字段的值不同而不同.
***********************************************************
-->
<!ELEMENT definition (#PCDATA|case)*>
<!ATTLIST definition dependent CDATA #IMPLIED>

<!--
***********************************************************
case元素内容指定definition的值,该值有四种选择:
 系统参数($开头),配置方式(#开头),实现Code2name接口类的类short名,
 实现Excelout接口类的类short名(以*开头).
 
 该元素含有属性oprtype,value,这些属性是必需的.
 oprtype属性指定依赖字段要进行的比较操作(只支持==,!=,>,<,>=,<=),
 value属性指定要进行比较操作的右操作符,依赖字段
 的值为左操作符.如台帐查询中,oprtype为"==",value为0时,
 表示如果sheetrestype==0为true时,则definition的值为该
 case元素的内容.
***********************************************************
-->
<!ELEMENT case (#PCDATA)>
<!ATTLIST case 
	oprtype CDATA #REQUIRED
	value CDATA #REQUIRED
>

<!ELEMENT headtitle (#PCDATA)>

<!ELEMENT endtitle (#PCDATA)>

<!ELEMENT beforewrite (#PCDATA)>

<!ELEMENT afterwrite (#PCDATA)>
<!--
end of excelout.dtd
-->

=== doorhinges0/SmartServer/common/target/classes/com/dtsjy/mdboss/common/export/config/entities.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE entity-config SYSTEM "entities.dtd" > -->
<!DOCTYPE entity-config[
<!--
<!DOCTYPE entity-config SYSTEM "entities.dtd">
************************************************************
该dtd文件用于说明entities.xml文件的配置方式

entity-config为文档元素,含有最少一个entity子元素
************************************************************
-->
<!ELEMENT entity-config (entity+)>

<!--
***********************************************************
 entity元素指定一个要导出数据的VO(对于多表查询的时候,因为有多个VO,所以
 需要使用复杂查询的方式,建立一个虚拟VO).
 entity元素的name属性是必须的,name的值应为VO的全类名,以保持唯一;exceloutbean属性指定用于导出操作
 的bean类全名,该类继承com.sunrise.boss.ui.resmanage.common.excelout.ExceloutBean类,若没有
 设置该属性,则程序中默认使用com.sunrise.boss.ui.resmanage.common.excelout.ExceloutBean类.
 entiy元素含有delegate,formname,resbundle,outfilename,fields子元素,
 除了delegate元素外,其它的子元素必须要依声明的顺序存在.
***********************************************************
-->
<!ELEMENT entity (tableorview?,delegate,fields,headtitle?,endtitle?,beforewrite?,afterwrite?)>
<!ATTLIST entity
			name ID #REQUIRED
			exceloutbean CDATA #IMPLIED
			showcount (yes|no) "no"
			sheetname CDATA #IMPLIED
>
<!--
***********************************************************
 delegate元素指定调用其方法获得查询数据及其记录数的代理类,该元素不是必需
 的,如果在excelout.xml文件没有指定,则程序中会使用
 "com.sunrise.boss.delegate.common.CommonDelegate"作为元素内容;

 delegate元素含有query,count两属性,query属性指定delegate类中用以获得
 查询数据的查询方法的名称,如果没有指定该属性的值程序中默认使用"doQuery"作为方法名;
 count属性指定delegate类中用以获得符合导出条件的 记录总数的方法名称,
 如果没有指定该属性的值,程序中默认使用"doCount"作为方法名.
***********************************************************
-->
<!ELEMENT tableorview (#PCDATA)>

<!ELEMENT delegate (query+)>
<!ATTLIST delegate
	class CDATA #REQUIRED
>

<!ELEMENT query (query_sql*)>
<!ATTLIST query
	methodtype (data_query|count_query) "data_query"
	methodname CDATA #REQUIRED
	querytype (normal|querybysql|querybynamesql) "normal"
	queryname CDATA #IMPLIED
	orderby CDATA #IMPLIED
>

<!ELEMENT query_sql (#PCDATA)>

<!ELEMENT formname (#PCDATA)>

<!--
***********************************************************
 指定VO的所有需要导出的字段,最少含有一个字段
***********************************************************
-->
<!ELEMENT fields (field+)>

<!--
***********************************************************
 指定需要导出的VO的单个字段,含有子元素definition,该子元素是可选的.

 name属性指定字段的名称(与VO里面定义一致).

 covertvalue属性指定该字段值在导出的时候是否需要进行转换,(譬如:套卡查询中,price字段导出
 的值为price/100),该属性的值只能是 字段名(+|-|*|/)数字的形式,若
 有特殊的实现,可以提供实现Excelout接口的实现类,实现接口的geValue
 方法.
 var属性指定值转换时需要赋值的变量(多个变量用逗号分隔),如若covertvalue的值为'price/100+addjust+receivable',
 则var的值应为'addjust,receivable',字段price的值默认添加.

 format与formattype属性用于定义导出数据的格式,如数字、日期的格式。
***********************************************************
-->
<!ELEMENT field (definition*)>
<!ATTLIST field
	name CDATA #REQUIRED
	covertvalue CDATA #IMPLIED
	var CDATA #IMPLIED
	format (none|STRING|NUMBER|DATE|CODE2NAME) "none"
	formattype CDATA #IMPLIED
	style CDATA #IMPLIED
	titlename CDATA #IMPLIED
	dbname CDATA #IMPLIED
>

<!--
***********************************************************
 指定导出字段进行code2name翻译时用到的definition属性的值.
 该元素可包含字符数据或case子元素.

 若包含字符数据,则该字符数据为definition的值[该值有四种选择:
 系统参数($开头),配置方式(#开头),实现Code2name接口类的类short名,
 实现Excelout接口的类short名(以*开头)];

 若包含case子元素,则definition的值由case元素的内容决定,此时,
 definition元素应含有属性dependent,指定definition的值依赖于哪
 个字段(同一VO的字段)譬如:台帐查询中,typeid字段翻译所用到的definition的
 值依赖于sheetrestype字段的值不同而不同.
***********************************************************
-->
<!ELEMENT definition (#PCDATA|case)*>
<!ATTLIST definition dependent CDATA #IMPLIED>

<!-- *********************************************************** case元素内容指定definition的值,该值有四种选择: 
	系统参数($开头),配置方式(#开头),实现Code2name接口类的类short名, 实现Excelout接口类的类short名(以*开头). 
	该元素含有属性oprtype,value,这些属性是必需的. oprtype属性指定依赖字段要进行的比较操作(只支持==,!=,>,<,>=,<=), 
	value属性指定要进行比较操作的右操作符,依赖字段 的值为左操作符.如台帐查询中,oprtype为"==",value为0时, 表示如果sheetrestype==0为true时,则definition的值为该 
	case元素的内容. *********************************************************** -->
<!ELEMENT case (#PCDATA)>
<!ATTLIST case
	oprtype CDATA #REQUIRED
	value CDATA #REQUIRED
>

<!ELEMENT headtitle (#PCDATA)>

<!ELEMENT endtitle (#PCDATA)>

<!ELEMENT beforewrite (#PCDATA)>

<!ELEMENT afterwrite (#PCDATA)>
<!-- end of excelout.dtd -->
]>
<entity-config>

	<entity name="com.sunrise.jop.business.system.user.role.persistent.RoleVO"
		sheetname="角色数据" showcount="yes">
		<delegate class="com.sunrise.jop.common.commoncontrol.CommonBO">
			<query methodname="doQuery" />
		</delegate>
		<fields>
			<field name="roleCode" titlename="角色编码 " format="STRING">
			</field>
			<field name="roleName" titlename="角色名称 " format="STRING">
			</field>
			<field name="orgCode" titlename="所属组织" format="CODE2NAME">
				<definition>#SYS_ORG</definition>
			</field>
			<field name="typeCode" titlename="角色类型" format="CODE2NAME">
				<definition>$ROLE_TYPE</definition>
			</field>
			<field name="roleState" titlename="角色状态" format="CODE2NAME">
				<definition>$PUB_STATUS</definition>
			</field>
			<field name="createtime" titlename="创建时间" format="DATE">
			</field>
			<field name="roleDesc" titlename="描述" format="STRING">
			</field>
		</fields>
		<headtitle>角色数据</headtitle>
	</entity>
	<entity name="com.sunrise.jop.business.system.org.org.persistent.OrgVO"
		sheetname="组织结构数据" showcount="yes">
		<delegate class="com.sunrise.jop.common.commoncontrol.CommonBO">
			<query methodname="doQuery" />
		</delegate>
		<fields>
			<field name="orgCode" titlename="组织编码 " format="STRING">
			</field>
			<field name="orgName" titlename="组织名称 " format="STRING">
			</field>
			<field name="orgTypeCode" titlename="组织类型" format="CODE2NAME">
				<definition>$ORG_TYPE</definition>
			</field>
			<field name="parentOrgCode" titlename="父组织" format="CODE2NAME">
				<definition dependent="parentOrgCode">
					<case oprtype="eq" value="-1">TREE_ROOT_NODE</case>
					<case oprtype="nq" value="-1">#SYS_ORG</case>
				</definition>
			</field>
			<field name="orgDesc" titlename="组织描述" format="STRING">
			</field>
		</fields>
		<headtitle>角色数据</headtitle>
	</entity>
	<entity
		name="com.sunrise.jop.business.system.function.businesslog.managelog.persistent.ManagelogVO"
		sheetname="管理日志数据" showcount="yes">
		<delegate class="com.sunrise.jop.common.commoncontrol.CommonBO">
			<query methodname="doQuery" />
		</delegate>
		<fields>
			<field name="logid" titlename="日志标识" format="STRING">
			</field>
			<field name="oprtime" titlename="操作时间 " format="DATE">
			</field>
			<field name="ip" titlename="IP" format="STRING">
			</field>
			<field name="oprcode" titlename="操作员" format="CODE2NAME">
				<definition>#OPERATOR</definition>
			</field>
			<field name="oprstate" titlename="操作结果" format="CODE2NAME">
				<definition>$SYS_OPRSTATE</definition>
			</field>
			<field name="opraction" titlename="操作动作" format="CODE2NAME">
				<definition>$SYS_OPRACTION</definition>
			</field>
			<field name="oprtype" titlename="操作对象" format="CODE2NAME">
				<definition>#MODULE</definition>
			</field>
			<field name="failcause" titlename="失败原因" format="STRING">
			</field>
			<field name="oprdata" titlename="操作数据" format="STRING">
			</field>
		</fields>
		<headtitle>角色数据</headtitle>
	</entity>
	<entity name="com.sunrise.jop.business.system.module.persistent.ModuleVO"
		sheetname="菜单数据" showcount="yes">
		<delegate class="com.sunrise.jop.common.commoncontrol.CommonBO">
			<query methodname="doQuery" />
		</delegate>
		<fields>
			<field name="moduleCode" titlename="模块编码" format="STRING">
			</field>
			<field name="moduleName" titlename="模块名称 " format="STRING">
			</field>
			<field name="moduleType" titlename="模块级别" format="CODE2NAME">
				<definition>MODULE_TYPE</definition>
			</field>
			<field name="parentCode" titlename="父模块名称" format="CODE2NAME">
				<definition dependent="parentCode">
					<case oprtype="eq" value="-1">TREE_ROOT_NODE</case>
					<case oprtype="nq" value="-1">#MODULE</case>
				</definition>
			</field>
			<field name="moduleUri" titlename="模块链接" format="STRING">
			</field>
			<field name="moduleView" titlename="是否显示" format="CODE2NAME">
				<definition>$PUB_YESNO</definition>
			</field>
			<field name="moduleDesc" titlename="模块描述" format="STRING">
			</field>
		</fields>
		<headtitle>模块数据</headtitle>
	</entity>
	<entity
		name="com.sunrise.jop.business.system.permission.perm.persistent.PermVO"
		sheetname="权限数据" showcount="yes">
		<delegate class="com.sunrise.jop.common.commoncontrol.CommonBO">
			<query methodname="doQuery" />
		</delegate>
		<fields>
			<field name="permCode" titlename="权限编码" format="STRING">
			</field>
			<field name="moduleCode" titlename="模块 " format="CODE2NAME">
				<definition>#MODULE</definition>
			</field>
			<field name="permTypeCode" titlename="权限类型" format="CODE2NAME">
				<definition>$SYS_PERMTYPE</definition>
			</field>
			<field name="permName" titlename="权限名称" format="STRING">
			</field>
			<field name="permDesc" titlename="权限描述" format="STRING">
			</field>
		</fields>
		<headtitle>权限数据</headtitle>
	</entity>
	<entity
		name="com.sunrise.jop.business.system.user.operator.persistent.OperatorVO"
		sheetname="操作员数据" showcount="yes">
		<delegate class="com.sunrise.jop.common.commoncontrol.CommonBO">
			<query methodname="doQuery" />
		</delegate>
		<fields>
			<field name="operId" titlename="工号" format="STRING">
			</field>
			<field name="operName" titlename="操作员名称" format="STRING">
			</field>
			<field name="state" titlename="状态" format="CODE2NAME">
				<definition>$PUB_STATUS</definition>
			</field>
			<field name="sex" titlename="性别" format="CODE2NAME">
				<definition>$PUB_SEX</definition>
			</field>
			<field name="orgCode" titlename="所属组织" format="CODE2NAME">
				<definition>#SYS_ORG</definition>
			</field>
			<field name="createtime" titlename="操作时间" format="DATE">
			</field>
			<field name="telno" titlename="联系电话" format="STRING">
			</field>
			<field name="memo" titlename="备注" format="STRING">
			</field>
		</fields>
		<headtitle>操作员数据</headtitle>
	</entity>

	<entity
